# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "gradle" # See documentation for possible values
    directory: "/services/account-service" # Location of package manifests
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle" # See documentation for possible values
    directory: "/services/fit-score-service" # Location of package manifests
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle" # See documentation for possible values
    directory: "/services/job-analyzer-service" # Location of package manifests
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle" # See documentation for possible values
    directory: "/services/prep-plan-service" # Location of package manifests
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle" # See documentation for possible values
    directory: "/services/profile-service" # Location of package manifests
    schedule:
      interval: "weekly"
