spring:
  data:
    mongodb:
      uri: mongodb://profile_user:secure_password@localhost:27017/profile_service?authSource=admin
      username: profile_user
      password: secure_password
      database: profile_service
