spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/account_service
    username: account_user
    password: secure_password

auth:
  jwt:
    privateKeyPath: /Users/diwakarbhatt/Projects/Job&InteviewCoPilot/secrets/jwt-keystore.p12
    publicKeyPath: /Users/diwakarbhatt/Projects/Job&InteviewCoPilot/secrets/jwt-public-key.pem
    privateKeyAlias: jwt-signing-key
    privateKeyPassword: changeit
    expirationSeconds: 3600
