spring:
  application:
    name: job-analyzer-service
  data:
    mongodb:
      database: job_analyzer_service
      auto-index-creation: true

server:
    port: 8083

management:
  endpoints:
    web:
      exposure:
        include: health,info

poller:
  id: job-analyser-1
  intervalMs: 30000
  lockTtlMs: 300000
  maxAttempts: 3
  workerThreads: 4
  queueSize: 50

profile-service:
  base-url: ${PROFILE_SERVICE_BASE_URL:http://localhost:8085}
